[Settings]
 ID = "4ea7f193-cea9-49b0-bb0b-606dc2e36851"
[[redirects]]
  from="/*"
  to="/index.html"
  status=200
[[headers]]
  for="/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; connect-src 'self' https://deep-chat-backend.herokuapp.com/; base-uri 'none'; manifest-src 'self'; object-src 'none'; img-src 'self'; script-src 'self' 'strict-dynamic' 'unsafe-inline' https://storage.googleapis.com/ 'sha256-GgRxrVOKNdB4LrRsVPDSbzvfdV4UqglmviH9GoBJ5jk='; style-src 'self' https://fonts.googleapis.com/ 'sha256-HKyJq3gUj/mqMkqWq85ZNpkmNgI6n3DNsUbeRzePVR8=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; font-src 'self' https://fonts.gstatic.com/ 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; frame-ancestors 'none'; form-action 'self'"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
