[Settings]
[[redirects]]
  from="/*"
  to="/index.html"
  status=200
[[headers]]
  for="/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; object-src 'none'; img-src 'self'; script-src 'self' https://storage.googleapis.com; style-src 'self'; font-src 'self'; frame-ancestors 'none';"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
